### ISSUE TITLE
Mise à jour de la version sur outilssgdf.github.io

### ISSUE THREAD

**Issue by HerKa2** [outilssgdf/analytiscout#55]
Bonjour,
Pouvez-vous mettre à jour la version mise à disposition sur https://outilssgdf.github.io/ ?
Merci.

**Comment by sbouchex** [comment]
C'est corrigé ! Merci

**Comment by HerKa2** [comment]
Cool, je n'arrive pas a générer l'exe avec maven.
C'est donc ma seule piste.
Merci pour le boulot :-)

**Comment by HerKa2** [comment]
Dans ton archive, il manque les jars
> Erreur : impossible de trouver ou de charger la classe principale org.leplan73.analytiscout.gui.GuiCmd
> Causé par : java.lang.ClassNotFoundException: org.leplan73.analytiscout.gui.GuiCmd

"ls" donne :
```
ls
analytiscout-assembly  analytiscout-gui  launch4j   pom.xml
analytiscout-cmd       analytiscout.iml  LICENSE    README.md
analytiscout-common    fichiers          notes.txt
```

**Comment by sbouchex** [comment]
Cette archive contient les sources uniquement. Il faut les builder pour lancer l'outil. Sinon, y'a une archive déjà faite sur https://github.com/outilssgdf/analytiscout/releases/download/1.3.1/analytiscout-1.3.1.zip, et y'a le sh qui va bien sous Linux/MacOS

**Comment by HerKa2** [comment]
j'ai proposé une correction dans le lanceur analytiscout-gui.sh pour passer le nom du jar de majuscule à minuscule

**Comment by sbouchex** [comment]
bien vu ! Grave erreur ! je corrige ça. Merci !
