### ISSUE TITLE
v1.3.1 : manque des compas dans l'onglet compa

### ISSUE THREAD

**Issue by HerKa2** [outilssgdf/analytiscout#57]
Dans l'excel "Jeunes"

- Les compas qui sont chefs en fonction principale et compa en fonction secondaire n'apparaissent pas dans l'onglet "Jeunes" du fichier "Jeunes". (pourtant ils apparaissent dans l'onglet "Compas" de l'excel "Responsables")
- Dans l'onglet "Effectifs", les branches F et R ne sont pas colorées.

Dans l'excel "Responsables"

- dans l'onglet "Compas", la couleur des AC et celle des Compas n'est pas la même
- La taille de la police est soit 11 soit 10.
- onglet "Aide", il manque un "s" à "re_ponsables farfadets" (ligne 15)

**Comment by sbouchex** [comment]
merci pour les remarques:
- Pour les compas qui manquent dans "jeunes" : C'est volontaires, on les a mis dans responsables car ils passent des formations / qualifs

pour le reste, je regarde

**Comment by sbouchex** [comment]
> "La taille de la police est soit 11 soit 10."

A quelle endroit ?

**Comment by sbouchex** [comment]
trouvé !
