### ISSUE TITLE
Dépendance jett-core 0.11.3

### ISSUE THREAD

**Issue by davidbotella** [outilssgdf/analytiscout#65]
Bonjour, le pom fait référence à la version 0.11.3 alors que la version actuelle sur github compile la version 0.11.1, d'où une erreur à la compilation.

[ERROR] Failed to execute goal on project analytiscout-common: Could not resolve dependencies for project org.leplan73:analytiscout-common:jar:1.4.0-SNAPSHOT: Could not find artifact net.sf.jett:jett-core:jar:0.11.3 in central (https://repo.maven.apache.org/maven2)

**Comment by sbouchex** [comment]
Oui, c'est normal. Dans le README, il est expliquer qu'il faut builder la branche "slf4j_migration" de jett pour pouvoir l'utiliser.
